import { existsSync, mkdirSync, writeFileSync, appendFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { randomUUID } from "node:crypto";
import type { Message } from "./types";
import { shouldCompact, collectToolNames, collectTouchedFiles } from "./compaction";

const PLUGIN_NAME = "auto-handoff";

function getHandoffDir(): string {
	return join(homedir(), ".cline", "data", "handoff");
}

function getSessionId(): string {
	return randomUUID().replace(/-/g, "").slice(0, 12);
}

function generateHandoffContent(
	sessionId: string,
	messages: Message[],
	tools: string[],
	files: string[],
): string {
	const timestamp = new Date().toISOString().replace("T", " ").slice(0, 19);
	const decisionLines: string[] = [];
	const unfinishedLines: string[] = [];

	for (const msg of messages) {
		if (msg.role !== "user" || typeof msg.content !== "string") continue;
		const text = msg.content;
		if (/\bdecision|accept|reject|adopt|roll.back|defer\b/i.test(text)) {
			const excerpt = text.slice(0, 120).replace(/\n/g, " ").trim();
			decisionLines.push(`  - ${excerpt}...`);
		}
		if (/\btodo|unfinished|next|remaining|still need\b/i.test(text)) {
			const excerpt = text.slice(0, 120).replace(/\n/g, " ").trim();
			unfinishedLines.push(`  - ${excerpt}...`);
		}
	}

	return [
		`# Handoff - Auto-generated (${sessionId})`,
		"",
		`> Auto-generated by ${PLUGIN_NAME} on ${timestamp}`,
		"",
		"## Summary",
		`- Session: ${sessionId}`,
		`- Messages analyzed: ${messages.length}`,
		`- Tools used: ${tools.length > 0 ? tools.join(", ") : "none"}`,
		`- Files touched: ${files.length > 0 ? files.join(", ") : "none"}`,
		"",
		"## Decisions Detected",
		decisionLines.length > 0 ? decisionLines.join("\n") : "  - (none detected)",
		"",
		"## Unfinished Items",
		unfinishedLines.length > 0 ? unfinishedLines.join("\n") : "  - (none detected)",
		"",
	].join("\n");
}

function generateIndexEntry(
	sessionId: string,
	handoffPath: string,
	messages: Message[],
	tools: string[],
): string {
	return JSON.stringify({
		schema_version: 1,
		source: PLUGIN_NAME,
		session_id: sessionId,
		timestamp: new Date().toISOString(),
		handoff_path: handoffPath,
		message_count: messages.length,
		tool_count: tools.length,
		file_count: 0,
	}) + "\n";
}

function writeHandoff(
	sessionId: string,
	messages: Message[],
	tools: string[],
	files: string[],
): string | null {
	try {
		const dir = getHandoffDir();
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}

		const handoffPath = join(dir, `${sessionId}.md`);
		const content = generateHandoffContent(sessionId, messages, tools, files);
		writeFileSync(handoffPath, content, "utf-8");

		const indexPath = join(dir, "index.jsonl");
		const indexEntry = generateIndexEntry(sessionId, handoffPath, messages, tools);
		appendFileSync(indexPath, indexEntry, "utf-8");

		console.log(`[${PLUGIN_NAME}] wrote handoff: ${handoffPath}`);
		return handoffPath;
	} catch (error) {
		console.error(`[${PLUGIN_NAME}] failed to write: ${String(error)}`);
		return null;
	}
}

export const plugin = {
	name: PLUGIN_NAME,
	manifest: {
		capabilities: ["messageBuilders"],
	},

	setup(api) {
		console.log(`[${PLUGIN_NAME}] setup() called`);

		try {
			const dir = getHandoffDir();
			if (!existsSync(dir)) {
				mkdirSync(dir, { recursive: true });
			}
			const markerPath = join(dir, "plugin-loaded.marker");
			writeFileSync(markerPath, `loaded at ${new Date().toISOString()}`, "utf-8");
			console.log(`[${PLUGIN_NAME}] marker: ${markerPath}`);
		} catch (error) {
			console.error(`[${PLUGIN_NAME}] dir setup: ${String(error)}`);
		}

		api.registerMessageBuilder({
			name: "detect-compact",
			build(messages) {
				const result = shouldCompact(messages);
				if (result.needsCompact) {
					const tools = collectToolNames(messages);
					const files = collectTouchedFiles(messages);
					const sessionId = getSessionId();
					writeHandoff(sessionId, messages, tools, files);
				}
				return messages;
			},
		});

		console.log(`[${PLUGIN_NAME}] setup() done`);
	},
};

export default plugin;
