import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import type { Message } from "./types";
import { shouldCompact, collectToolNames, collectTouchedFiles } from "./compaction";
import { ToolCallRecorder } from "./tool-recorder";
import { buildHandoffRuleContent, handoffFilename } from "./rules-injector";

const PLUGIN_NAME = "auto-handoff";

function getHandoffDir(): string {
	return join(homedir(), ".cline", "data", "handoff");
}

function generateHandoffContent(
	messages: Message[],
	tools: string[],
	files: string[],
): string {
	const timestamp = new Date().toISOString().replace("T", " ").slice(0, 19);
	const decisionLines: string[] = [];
	const unfinishedLines: string[] = [];

	for (const msg of messages) {
		if (msg.role !== "user" || typeof msg.content !== "string") continue;
		const text = msg.content;
		if (/\bdecision|accept|reject|adopt|roll.back|defer\b/i.test(text)) {
			const excerpt = text.slice(0, 120).replace(/\n/g, " ").trim();
			decisionLines.push(`  - ${excerpt}...`);
		}
		if (/\btodo|unfinished|next|remaining|still need\b/i.test(text)) {
			const excerpt = text.slice(0, 120).replace(/\n/g, " ").trim();
			unfinishedLines.push(`  - ${excerpt}...`);
		}
	}

	return [
		`# Handoff`,
		"",
		`> Auto-generated by ${PLUGIN_NAME} on ${timestamp}`,
		"",
		"## Summary",
		`- Messages analyzed: ${messages.length}`,
		`- Tools used: ${tools.length > 0 ? tools.join(", ") : "none"}`,
		`- Files touched: ${files.length > 0 ? files.join(", ") : "none"}`,
		"",
		"## Decisions Detected",
		decisionLines.length > 0 ? decisionLines.join("\n") : "  - (none detected)",
		"",
		"## Unfinished Items",
		unfinishedLines.length > 0 ? unfinishedLines.join("\n") : "  - (none detected)",
		"",
	].join("\n");
}

function writeHandoff(
	messages: Message[],
	tools: string[],
	files: string[],
	workspacePath: string,
): string | null {
	try {
		const dir = getHandoffDir();
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}

		const filename = handoffFilename(workspacePath);
		const handoffPath = join(dir, filename);
		const content = generateHandoffContent(messages, tools, files);
		writeFileSync(handoffPath, content, "utf-8");

		console.log(`[${PLUGIN_NAME}] wrote handoff: ${handoffPath}`);
		return handoffPath;
	} catch (error) {
		console.error(`[${PLUGIN_NAME}] failed to write handoff: ${String(error)}`);
		return null;
	}
}

// ─── Plugin Entry ───

const toolRecorder = new ToolCallRecorder();

export const plugin = {
	name: PLUGIN_NAME,
	manifest: {
		capabilities: ["messageBuilders", "rules", "hooks"],
	},

	setup(api: any, ctx?: any) {
		console.log(`[${PLUGIN_NAME}] setup() called`);

		// ── Marker file ──
		try {
			const dir = getHandoffDir();
			if (!existsSync(dir)) {
				mkdirSync(dir, { recursive: true });
			}
			writeFileSync(join(dir, "plugin-loaded.marker"), `loaded at ${new Date().toISOString()}`, "utf-8");
		} catch (error) {
			console.error(`[${PLUGIN_NAME}] marker setup: ${String(error)}`);
		}

		// ── 1. compact-observer: log compact events, do NOT write handoff ──
		api.registerMessageBuilder({
			name: "compact-observer",
			build(messages: Message[]) {
				const result = shouldCompact(messages);
				if (result.needsCompact) {
					const tools = collectToolNames(messages);
					const files = collectTouchedFiles(messages);
					console.log(
						`[${PLUGIN_NAME}] compact detected — ` +
						`${result.totalTokens} tokens, ${messages.length} msgs, ` +
						`${tools.length} tools, ${files.length} files. ` +
						`Handoff is now a separate mechanism (ADR-005).`
					);
				}
				return messages;
			},
		});

		// ── 2. rules injection: dynamic handoff context for new sessions ──
		//    content is a function — called each time the rule is evaluated.
		//    setup() runs once, but the function re-reads the latest handoff.
		const workspacePath = ctx?.workspacePath ?? process.cwd();
		api.registerRule({
			name: "handoff-context",
			content: () => buildHandoffRuleContent(workspacePath),
		});

		// ── 3. hooks: tool-call-recorder (beforeTool + afterTool) ──
		//    Unified data source for #1 (slow call detection) and #4 (loop guard).
		//    Hooks are registered via the plugin.hooks field, not api.
		//    Note: plugin hooks are set on the plugin object itself (see below).

		console.log(`[${PLUGIN_NAME}] setup() done — capabilities: messageBuilders, rules, hooks`);
	},

	// ── Hooks (registered on plugin object, not via api) ──
	hooks: {
		beforeTool(args: { toolName: string; input: Record<string, unknown> }) {
			toolRecorder.beforeTool(args.toolName, args.input);
		},

		afterTool(args: { toolName: string; success: boolean }) {
			const record = toolRecorder.afterTool(args.toolName, args.success);
			if (!record) return;

			// #1: Slow call detection
			if (record.duration > 30_000) {
				console.warn(
					`[${PLUGIN_NAME}] SLOW TOOL: ${record.name} took ${(record.duration / 1000).toFixed(1)}s`
				);
			}

			// #4: Repetition detection
			const rep = toolRecorder.detectRepetition(5, 3);
			if (rep.repeating) {
				console.warn(
					`[${PLUGIN_NAME}] LOOP DETECTED: pattern [${rep.pattern.join(" → ")}] repeated ${rep.count}x`
				);
				// Injection of warning into messages is handled by beforeModel hook (Phase 3)
				// For now, just log. The detection data is available via toolRecorder.getHistory().
			}
		},
	},
};

export default plugin;
