import type { AgentPlugin } from "@cline/core";
import { shouldCompact, collectToolNames, collectTouchedFiles, MAX_INPUT_TOKENS, COMPACT_AT_RATIO } from "./compaction.js";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

const HOST_NAME = "handoff-plugin";
const SCHEMA_VERSION = 1;

function getLogPath(): string {
	const dir = path.join(os.homedir(), ".cline", "data", "handoff");
	try {
		fs.mkdirSync(dir, { recursive: true });
	} catch {
		return "";
	}
	return dir;
}

function logError(label: string, err: unknown): void {
	const msg = `[handoff-plugin] ${label}: ${err instanceof Error ? err.message : String(err)}`;
	console.error(msg);
	try {
		const logDir = path.join(os.homedir(), ".cline", "data", "handoff");
		const logPath = path.join(logDir, "plugin-errors.log");
		fs.mkdirSync(logDir, { recursive: true });
		fs.appendFileSync(logPath, `${new Date().toISOString()} ${msg}\n`, "utf-8");
	} catch {
	}
}

function getHandoffDir(): string {
	const dir = path.join(os.homedir(), ".cline", "data", "handoff");
	try {
		fs.mkdirSync(dir, { recursive: true });
		return dir;
	} catch (e) {
		logError("getHandoffDir/mkdir", e);
		return "";
	}
}

function writeTestMarker(dir: string): void {
	const markerPath = path.join(dir, "plugin-loaded.marker");
	try {
		fs.writeFileSync(markerPath, JSON.stringify({
			loaded: true,
			timestamp: new Date().toISOString(),
			host: HOST_NAME,
		}, null, 2), "utf-8");
	} catch (e) {
		logError("writeTestMarker", e);
	}
}

function writeHandoff(dir: string, sessionId: string, messages: import("./compaction.js").CompactResult): void {
	const toolNames = collectToolNames(messages.messages);
	const filePaths = collectTouchedFiles(messages.messages);
	const handoffPath = path.join(dir, `${sessionId}.md`);
	const content = `# Handoff — ${sessionId}

> Auto-generated by ${HOST_NAME}

## Session Info
- Session ID: \`${sessionId}\`
- Timestamp: ${new Date().toISOString()}
- Total tokens before compact: ${messages.totalTokens}
- Input token budget: ${MAX_INPUT_TOKENS}
- Compact threshold: ${COMPACT_AT_RATIO}

## Tools Used
${toolNames.length > 0 ? toolNames.map((t) => `- \`${t}\``).join("\n") : "- none"}

## Files Touched
${filePaths.length > 0 ? filePaths.map((p) => `- ${p}`).join("\n") : "- none"}
`;
	try {
		fs.writeFileSync(handoffPath, content, "utf-8");
	} catch (e) {
		logError("writeHandoff", e);
	}
}

function appendIndex(dir: string, sessionId: string, handoffPath: string, toolCount: number, fileCount: number): void {
	const indexEntry = {
		schema_version: SCHEMA_VERSION,
		source: HOST_NAME,
		session_id: sessionId,
		timestamp: new Date().toISOString(),
		handoff_path: handoffPath,
		tool_count: toolCount,
		file_count: fileCount,
	};
	const indexFile = path.join(dir, "index.jsonl");
	try {
		fs.appendFileSync(indexFile, JSON.stringify(indexEntry) + "\n", "utf-8");
	} catch (e) {
		logError("appendIndex", e);
	}
}

function writeSetupDiagnostic(ok: boolean, error: string): void {
	try {
		const dir = path.join(os.homedir(), ".cline", "data", "handoff");
		fs.mkdirSync(dir, { recursive: true });
		fs.writeFileSync(path.join(dir, "setup-diagnostic.json"), JSON.stringify({
			setup_ok: ok,
			error: error,
			timestamp: new Date().toISOString(),
			node: process.version,
			cwd: process.cwd(),
		}, null, 2), "utf-8");
	} catch {
	}
}

export const plugin: AgentPlugin = {
	name: "handoff-plugin",
	manifest: {
		capabilities: ["messageBuilders"],
	},

	setup(api) {
		let setupOk = false;
		let setupError = "";
		try {
			const handoffDir = getHandoffDir();
			if (handoffDir) {
				writeTestMarker(handoffDir);
			}

			api.registerMessageBuilder({
				name: "compact-and-handoff",
				build(messages) {
					const result = shouldCompact(messages);
					if (!result.needsCompact) {
						return messages;
					}
					const sessionId = `session-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
					if (handoffDir) {
						writeHandoff(handoffDir, sessionId, result);
						const toolCount = collectToolNames(result.messages).length;
						const fileCount = collectTouchedFiles(result.messages).length;
						appendIndex(handoffDir, sessionId, `${sessionId}.md`, toolCount, fileCount);
					}
					return result.messages;
				},
			});
			setupOk = true;
		} catch (e) {
			setupError = e instanceof Error ? e.message : String(e);
			console.error(`[handoff-plugin] setup failed:`, e);
		}
		writeSetupDiagnostic(setupOk, setupError);
	},
};

export default plugin;
