import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Message } from "./types";
import { PLUGIN_NAME, getSnapshotDir } from "./constants";
import { snapshotFilename } from "./rules-injector";

// ─── Data Extraction ───

interface ExtractedDecision {
	text: string;
	status: string;
}

interface ExtractedUnfinished {
	direction: string;
	priority: string;
}

/**
 * Extract decision signals from message history.
 * Looks for explicit accept/reject/adopt patterns in user messages.
 */
function extractDecisions(messages: Message[]): ExtractedDecision[] {
	const decisions: ExtractedDecision[] = [];
	const decisionPattern = /\b(accept|reject|adopt|defer|roll\s*back|approved?|declined?)\b/i;

	for (const msg of messages) {
		if (msg.role !== "user") continue;
		const text = typeof msg.content === "string" ? msg.content : "";
		const match = text.match(decisionPattern);
		if (match) {
			const keyword = match[1].toLowerCase();
			const status = /^(accept|adopt|approve)/.test(keyword) ? "accepted"
				: /^(reject|decline)/.test(keyword) ? "rejected"
				: /^defer/.test(keyword) ? "deferred"
				: /^roll/.test(keyword) ? "rolled back"
				: "decided";
			const excerpt = text.slice(0, 100).replace(/\n/g, " ").trim();
			decisions.push({ text: excerpt, status });
		}
	}

	return decisions;
}

/**
 * Extract unfinished items / next steps from message history.
 * Looks for TODO-like patterns in user messages.
 */
function extractUnfinished(messages: Message[]): ExtractedUnfinished[] {
	const items: ExtractedUnfinished[] = [];
	const todoPattern = /\b(todo|unfinished|next|remaining|still need|pending|follow[- ]up)\b/i;

	for (const msg of messages) {
		if (msg.role !== "user") continue;
		const text = typeof msg.content === "string" ? msg.content : "";
		if (todoPattern.test(text)) {
			const excerpt = text.slice(0, 100).replace(/\n/g, " ").trim();
			items.push({ direction: excerpt, priority: "TBD" });
		}
	}

	return items;
}

/**
 * Extract authoritative sources — file paths referenced in tool_use blocks
 * that look like documentation or design documents.
 */
function extractSources(files: string[]): string[] {
	const sources = new Set<string>();
	const docPattern = /\.(md|txt|json|yaml|yml)$/i;

	for (const file of files) {
		if (docPattern.test(file)) {
			sources.add(file);
		}
	}

	return [...sources].slice(0, 10);
}

/**
 * Derive a session title from the first user message.
 */
function deriveSessionTitle(messages: Message[]): string {
	for (const msg of messages) {
		if (msg.role === "user" && typeof msg.content === "string") {
			const text = msg.content.trim();
			return text.length > 60 ? text.slice(0, 57) + "..." : text;
		}
	}
	return "Untitled Session";
}

// ─── Snapshot Generation ───

/**
 * Generate context snapshot content using the 5-section template
 * from design.md §3.3.1.
 */
export function generateSnapshotContent(
	messages: Message[],
	tools: string[],
	files: string[],
): string {
	const timestamp = new Date().toISOString().replace("T", " ").slice(0, 19);
	const title = deriveSessionTitle(messages);
	const decisions = extractDecisions(messages);
	const unfinished = extractUnfinished(messages);
	const sources = extractSources(files);

	const sections: string[] = [];

	// Header
	sections.push(`# Context Snapshot — ${title}`);
	sections.push("");
	sections.push(`> Auto-generated by ${PLUGIN_NAME} on ${timestamp}`);
	sections.push(`> Messages analyzed: ${messages.length} | Tools used: ${tools.length} | Files touched: ${files.length}`);
	sections.push("");

	// §1: Decisions
	sections.push("## 本会话决策");
	sections.push("");
	if (decisions.length > 0) {
		sections.push("| 决策 | 状态 |");
		sections.push("|------|------|");
		for (const d of decisions) {
			sections.push(`| ${d.text} | ${d.status} |`);
		}
	} else {
		sections.push("_No explicit decisions detected in this session._");
	}
	sections.push("");

	// §2: Net Changes
	sections.push("## 本会话净变化");
	sections.push("");
	if (files.length > 0) {
		sections.push("**Files:**");
		for (const f of files) {
			sections.push(`- \`${f}\``);
		}
	} else {
		sections.push("_No file changes detected._");
	}
	sections.push("");
	if (tools.length > 0) {
		sections.push("**Tools:**");
		sections.push(tools.map((t) => `\`${t}\``).join(", "));
	}
	sections.push("");

	// §3: Unfinished Items
	sections.push("## 未完成项 / 后续动作");
	sections.push("");
	if (unfinished.length > 0) {
		sections.push("| 方向 | 说明 | 优先级 |");
		sections.push("|------|------|--------|");
		for (const u of unfinished) {
			sections.push(`| ${u.direction} | — | ${u.priority} |`);
		}
	} else {
		sections.push("_No unfinished items detected._");
	}
	sections.push("");

	// §4: Authoritative Sources
	sections.push("## 权威源");
	sections.push("");
	if (sources.length > 0) {
		for (const s of sources) {
			sections.push(`- \`${s}\``);
		}
	} else {
		sections.push("_No authoritative sources referenced._");
	}
	sections.push("");

	return sections.join("\n");
}

// ─── Snapshot Write ───

/**
 * Write a context snapshot to disk.
 * Called by compact-observer when needsCompact is true.
 *
 * @returns The path of the written snapshot, or null on failure.
 */
export function writeSnapshot(
	messages: Message[],
	tools: string[],
	files: string[],
	workspacePath: string,
): string | null {
	try {
		const dir = getSnapshotDir();
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}

		const filename = snapshotFilename(workspacePath);
		const snapshotPath = join(dir, filename);
		const content = generateSnapshotContent(messages, tools, files);
		writeFileSync(snapshotPath, content, "utf-8");

		return snapshotPath;
	} catch (error) {
		console.error(`[${PLUGIN_NAME}] failed to write snapshot: ${String(error)}`);
		return null;
	}
}
