import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Message, SnapshotData } from "./types";
import { PLUGIN_NAME, getSnapshotDir } from "./constants";
import { snapshotFilename } from "./rules-injector";
import { decisionExtractor, changeExtractor, todoExtractor, sourceExtractor } from "./extractors";
import { formatConfidence, formatPriority } from "./formatter";

// ─── Helpers ───

function groupBy<T>(items: T[], key: keyof T): Record<string, T[]> {
	const result: Record<string, T[]> = {};
	for (const item of items) {
		const k = String(item[key]);
		if (!result[k]) result[k] = [];
		result[k].push(item);
	}
	return result;
}

// ─── v0.7.0 Data Extraction ───

/**
 * Derive a session title from the first user message.
 */
function deriveSessionTitle(messages: Message[]): string {
	for (const msg of messages) {
		if (msg.role === "user" && typeof msg.content === "string") {
			const text = msg.content.trim();
			return text.length > 60 ? text.slice(0, 57) + "..." : text;
		}
	}
	return "Untitled Session";
}

/**
 * Extract structured snapshot data using v0.7.0 extractors.
 * Data/render decoupling: this function produces SnapshotData, renderSnapshot consumes it.
 * Extractors return pre-sorted data (business logic lives in extractors, not renderers).
 */
export function extractSnapshotData(
	messages: Message[],
	tools: string[],
	files: string[],
): SnapshotData {
	return {
		meta: {
			title: deriveSessionTitle(messages),
			timestamp: new Date().toISOString().replace("T", " ").slice(0, 19),
			messageCount: messages.length,
			toolCount: tools.length,
			fileCount: files.length,
		},
		decisions: decisionExtractor.extract(messages, tools, files),
		changes: changeExtractor.extract(messages, tools, files),
		todos: todoExtractor.extract(messages, tools, files),
		sources: sourceExtractor.extract(messages, tools, files),
	};
}

// ─── v0.7.0 Rendering (pure templates) ───

function renderHeader(meta: SnapshotData["meta"]): string {
	return [
		`# Context Snapshot — ${meta.title}`,
		"",
		`> Auto-generated by ${PLUGIN_NAME} on ${meta.timestamp}`,
		`> Messages analyzed: ${meta.messageCount} | Tools used: ${meta.toolCount} | Files touched: ${meta.fileCount}`,
	].join("\n");
}

function renderDecisions(decisions: SnapshotData["decisions"]): string {
	if (decisions.length === 0) {
		return "## 本会话决策\n\n_No explicit decisions detected in this session._";
	}

	const rows = decisions.map(
		(d) => `| ${d.text} | ${d.status} | ${formatConfidence(d.confidence)} |`,
	);

	return [
		"## 本会话决策",
		"",
		"| 决策 | 状态 | 置信度 |",
		"|------|------|--------|",
		...rows,
	].join("\n");
}

function renderChanges(changes: SnapshotData["changes"]): string {
	const grouped = groupBy(changes, "kind");
	const fileKinds = ["file-created", "file-modified", "file-deleted"] as const;
	const hasFiles = fileKinds.some((k) => grouped[k]?.length);
	const hasTools = grouped["tool-used"]?.length;

	if (!hasFiles && !hasTools) {
		return "## 本会话净变化\n\n_No changes detected._";
	}

	const parts: string[] = ["## 本会话净变化", ""];

	if (hasFiles) {
		parts.push("**Files:**");
		for (const kind of fileKinds) {
			for (const c of grouped[kind] ?? []) {
				parts.push(`- \`${c.path}\``);
			}
		}
	}

	if (hasTools) {
		if (hasFiles) parts.push("");
		parts.push("**Tools:**");
		parts.push(grouped["tool-used"]!.map((c) => `\`${c.toolName}\``).join(", "));
	}

	return parts.join("\n");
}

function renderTodos(todos: SnapshotData["todos"]): string {
	if (todos.length === 0) {
		return "## 未完成项 / 后续动作\n\n_No unfinished items detected._";
	}

	const rows = todos.map(
		(t) => `| ${t.direction} | ${formatPriority(t.priority)} | ${formatConfidence(t.confidence)} |`,
	);

	return [
		"## 未完成项 / 后续动作",
		"",
		"| 方向 | 优先级 | 置信度 |",
		"|------|--------|--------|",
		...rows,
	].join("\n");
}

function renderSources(sources: SnapshotData["sources"]): string {
	if (sources.length === 0) {
		return "## 权威源\n\n_No authoritative sources referenced._";
	}

	const byKind = groupBy(sources, "kind");
	const parts: string[] = ["## 权威源", ""];

	for (const kind of ["doc", "source-code", "config", "external"] as const) {
		const items = byKind[kind];
		if (items?.length) {
			for (const s of items) {
				parts.push(`- \`${s.path}\``);
			}
		}
	}

	return parts.join("\n");
}

/**
 * Render SnapshotData to Markdown (5-section template from design.md §3.3.1).
 * Sections are self-contained; spacing is controlled here, not by section functions.
 * Data is pre-sorted by extractors; renderer is a pure template.
 */
export function renderSnapshot(data: SnapshotData): string {
	return [
		renderHeader(data.meta),
		renderDecisions(data.decisions),
		renderChanges(data.changes),
		renderTodos(data.todos),
		renderSources(data.sources),
	].join("\n\n");
}

// ─── Snapshot Write (v0.7.0 pipeline) ───

/**
 * Write a context snapshot to disk.
 * Uses v0.7.0 extract→render pipeline.
 *
 * @returns The path of the written snapshot, or null on failure.
 */
export function writeSnapshot(
	messages: Message[],
	tools: string[],
	files: string[],
	workspacePath: string,
): string | null {
	try {
		const dir = getSnapshotDir();
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}

		const filename = snapshotFilename(workspacePath);
		const snapshotPath = join(dir, filename);
		const data = extractSnapshotData(messages, tools, files);
		const content = renderSnapshot(data);
		writeFileSync(snapshotPath, content, "utf-8");

		return snapshotPath;
	} catch (error) {
		console.error(`[${PLUGIN_NAME}] failed to write snapshot: ${String(error)}`);
		return null;
	}
}
