import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Message, SnapshotData } from "./types";
import { PLUGIN_NAME, getSnapshotDir } from "./constants";
import { snapshotFilename } from "./rules-injector";
import { decisionExtractor, changeExtractor, todoExtractor, sourceExtractor } from "./extractors";

// ─── v0.7.0 Data Extraction ───

/**
 * Derive a session title from the first user message.
 */
function deriveSessionTitle(messages: Message[]): string {
	for (const msg of messages) {
		if (msg.role === "user" && typeof msg.content === "string") {
			const text = msg.content.trim();
			return text.length > 60 ? text.slice(0, 57) + "..." : text;
		}
	}
	return "Untitled Session";
}

/**
 * Extract structured snapshot data using v0.7.0 extractors.
 * Data/render decoupling: this function produces SnapshotData, renderSnapshot consumes it.
 */
export function extractSnapshotData(
	messages: Message[],
	tools: string[],
	files: string[],
): SnapshotData {
	return {
		meta: {
			title: deriveSessionTitle(messages),
			timestamp: new Date().toISOString().replace("T", " ").slice(0, 19),
			messageCount: messages.length,
			toolCount: tools.length,
			fileCount: files.length,
		},
		decisions: decisionExtractor.extract(messages, tools, files),
		changes: changeExtractor.extract(messages, tools, files),
		todos: todoExtractor.extract(messages, tools, files),
		sources: sourceExtractor.extract(messages, tools, files),
	};
}

// ─── v0.7.0 Rendering ───

/**
 * Render SnapshotData to Markdown (5-section template from design.md §3.3.1).
 * Sorts by confidence (high first) within each section.
 */
export function renderSnapshot(data: SnapshotData): string {
	const { meta, decisions, changes, todos, sources } = data;
	const sections: string[] = [];

	// Header
	sections.push(`# Context Snapshot — ${meta.title}`);
	sections.push("");
	sections.push(`> Auto-generated by ${PLUGIN_NAME} on ${meta.timestamp}`);
	sections.push(`> Messages analyzed: ${meta.messageCount} | Tools used: ${meta.toolCount} | Files touched: ${meta.fileCount}`);
	sections.push("");

	// §1: Decisions (sorted by confidence: high → medium → low)
	sections.push("## 本会话决策");
	sections.push("");
	if (decisions.length > 0) {
		sections.push("| 决策 | 状态 | 置信度 |");
		sections.push("|------|------|--------|");
		const sorted = [...decisions].sort(confidenceOrder);
		for (const d of sorted) {
			const conf = d.confidence === "low" ? " ⚠️ low" : d.confidence === "medium" ? " medium" : "";
			sections.push(`| ${d.text} | ${d.status} | ${conf} |`);
		}
	} else {
		sections.push("_No explicit decisions detected in this session._");
	}
	sections.push("");

	// §2: Net Changes (file-* first, tool-used after; deduplicated)
	sections.push("## 本会话净变化");
	sections.push("");
	const fileChanges = changes.filter((c) => c.kind.startsWith("file-"));
	const toolChanges = changes.filter((c) => c.kind === "tool-used");

	if (fileChanges.length > 0) {
		sections.push("**Files:**");
		for (const c of fileChanges) {
			sections.push(`- \`${c.path}\``);
		}
	} else {
		sections.push("_No file changes detected._");
	}
	sections.push("");
	if (toolChanges.length > 0) {
		sections.push("**Tools:**");
		sections.push(toolChanges.map((c) => `\`${c.toolName}\``).join(", "));
	}
	sections.push("");

	// §3: Unfinished Items (sorted by priority)
	sections.push("## 未完成项 / 后续动作");
	sections.push("");
	if (todos.length > 0) {
		sections.push("| 方向 | 优先级 | 置信度 |");
		sections.push("|------|--------|--------|");
		const sorted = [...todos].sort(priorityOrder);
		for (const t of sorted) {
			const pri = t.priority === "high" ? "🔴" : t.priority === "medium" ? "🟡" : "🟢";
			const conf = t.confidence === "low" ? " ⚠️" : "";
			sections.push(`| ${t.direction} | ${pri} ${t.priority} | ${conf} |`);
		}
	} else {
		sections.push("_No unfinished items detected._");
	}
	sections.push("");

	// §4: Authoritative Sources (grouped by kind)
	sections.push("## 权威源");
	sections.push("");
	if (sources.length > 0) {
		const byKind = groupBy(sources, "kind");
		for (const kind of ["doc", "source-code", "config", "external"] as const) {
			const items = byKind[kind];
			if (items && items.length > 0) {
				for (const s of items) {
					sections.push(`- \`${s.path}\``);
				}
			}
		}
	} else {
		sections.push("_No authoritative sources referenced._");
	}
	sections.push("");

	return sections.join("\n");
}

// ─── Helpers ───

function confidenceOrder(a: { confidence: string }, b: { confidence: string }): number {
	const order = { high: 0, medium: 1, low: 2 };
	return (order[a.confidence as keyof typeof order] ?? 3) - (order[b.confidence as keyof typeof order] ?? 3);
}

function priorityOrder(a: { priority: string }, b: { priority: string }): number {
	const order = { high: 0, medium: 1, low: 2, tbd: 3 };
	return (order[a.priority as keyof typeof order] ?? 4) - (order[b.priority as keyof typeof order] ?? 4);
}

function groupBy<T>(items: T[], key: keyof T): Record<string, T[]> {
	const result: Record<string, T[]> = {};
	for (const item of items) {
		const k = String(item[key]);
		if (!result[k]) result[k] = [];
		result[k].push(item);
	}
	return result;
}

// ─── Snapshot Write (v0.7.0 pipeline) ───

/**
 * Write a context snapshot to disk.
 * Uses v0.7.0 extract→render pipeline.
 *
 * @returns The path of the written snapshot, or null on failure.
 */
export function writeSnapshot(
	messages: Message[],
	tools: string[],
	files: string[],
	workspacePath: string,
): string | null {
	try {
		const dir = getSnapshotDir();
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}

		const filename = snapshotFilename(workspacePath);
		const snapshotPath = join(dir, filename);
		const data = extractSnapshotData(messages, tools, files);
		const content = renderSnapshot(data);
		writeFileSync(snapshotPath, content, "utf-8");

		return snapshotPath;
	} catch (error) {
		console.error(`[${PLUGIN_NAME}] failed to write snapshot: ${String(error)}`);
		return null;
	}
}
